let constants = {
    'LOAD_BOOKS_SUCCESS' : 'LOAD_BOOKS_SUCCESS',
    'LOAD_BOOKS' : 'LOAD_BOOKS',
    'LOAD_BOOKS_FAILURE' : 'LOAD_BOOKS_FAILURE',

    'SEARCH_BOOK_SUCCESS' : 'SEARCH_BOOK_SUCCESS',

    'EDIT_BOOK' : 'EDIT_BOOK' ,
    'EDIT_BOOK_SUCCESS' : 'EDIT_BOOK_SUCCESS'
}; 

export default constants; 
